### ISSUE TITLE
Using the -e switch in Windows - Question

### ISSUE THREAD

**Issue by TanMan1217** [slhck/ffmpeg-normalize#70] opened 2018-05-05 03:41 UTC
I want to normalize my playlist using ffmpeg-normalize. My playlist is currently MP3 VBR encoded with the -V2 switch. I'd like to keep the files encoded the same way. In ffmpeg, I'd do that with "-c:a libmp3lame -q:a 2". Even though ffmpeg-normalize doesn't include a VBR option, it uses the -e switch to pass parameters directly to ffmpeg. So in theory I should be able to do this:

ffmpeg-normalize "song.mp3" -c:a libmp3lame -e "q:a 2"

But it pukes on the -e switch. With debug, I can see that the string is being interpreted with json, so I've tried formatting it as json, but the formatting is messing me up. The string should look like this:

{"q:a":"2"}

But I'm pretty sure I'm being clobbered by some combination of the Windows command processor and the json parser. I've tried quoting the entire string and escaping the embedded quotes (using caret, forward slash, back slash, and double quotes), and I've tried single quotes as the outer quotes, but I can't get this to work.

Can anyone please explain to me how to format the -e switch in Windows?

**Comment by slhck** [comment] 2018-05-05 08:28
As written in the example, you have to supply a JSON-formatted list of options, that is:

```bash
ffmpeg-normalize "song.mp3" -c:a libmp3lame -e '["-q:a", "2"]'
```

I had a small error in the description where the leading dash was missing. This is now fixed; you should always be able to specify arguments as you would for `ffmpeg`.

That said, if you want to normalize MP3s without actually re-converting them, I'd recommend looking at [MP3Gain](http://mp3gain.sourceforge.net/) instead.

**Comment by TanMan1217** [comment] 2018-05-05 13:42
Thanks for your reply and the correction of my labels on this post, but I started with the example from the doc. I tried your example and got this error:

ffmpeg-normalize: error: unrecognized arguments: 2]'

Did you perhaps try this on Windows yourself? I believe the problem is the single quotes are not a valid string delimiter in the Windows Command shell, so it's not being passed to ffmpeg-normalize as expected. And therefore the colon in the parm is being taken by JSON as a separator.

**Comment by slhck** [comment] 2018-05-05 15:10
No, unfortunately I don't have Windows here. You may try escaping the quote with a backslash?

**Comment by TanMan1217** [comment] 2018-05-05 15:17
In my initial post, I said:

"I've tried quoting the entire string and escaping the embedded quotes (using caret, forward slash, back slash, and double quotes)"

I'm installing Ubuntu for Windows now so I can get this working. I'm almost done with that. I'll post back with the results.

**Comment by slhck** [comment] 2018-05-05 15:26
Ah, sorry, I kind of skimmed over that. Honestly I don't know how to do the escaping on Windows, as that syntax [is quite weird](https://stackoverflow.com/a/15262019/435093) — here, double-quoting (as in “using two quotes”) the double-quote seems to be an option.

**Comment by TanMan1217** [comment] 2018-05-05 15:52
Yup, I tried double quoting, but to no avail. I just finished setting up all the prerequisites and getting ffmpeg-normalize to work under that Ubuntu, and it's working. So the problem is definitely Windows related.

If I get some time, I'll fork the project and change the way the -e is handled to bypass json. IMHO, that string should just be passed as is to ffmpeg, and not parsed at all.

**Comment by slhck** [comment] 2018-05-05 15:58
I'm absolutely open to PRs to make the extra options simpler. (In fact, the pre-1.0 version of `ffmpeg-normalize` allowed this, since I used the `docopt` package for parsing options at the time, but it wasn't as flexible as `argparse`.)

The problem with Python's `argparse` is that it does not parse such “list of options” options correctly when they start with a dash. You can read about that [here](https://stackoverflow.com/questions/45541581/using-argparse-with-argument-values-that-begin-with-a-dash). That's why I went for a JSON list syntax.

One alternative would be to have people use the `=` sign.

**Comment by TanMan1217** [comment] 2018-05-05 16:08
I strongly agree that using argparse and changing the syntax to use the = sign (as in 'e="-q:a 2"' is the right way to handle this parm. That's actually the updated answer of that post you linked to.

**Comment by slhck** [comment] 2018-05-05 16:25
Yup, this is now possible in 1.3.4.

You can use the old JSON syntax with `-e "[ … ]"` or the new `-e="-foo -bar"` syntax.

**Comment by TanMan1217** [comment] 2018-05-05 17:31
json is still the problem. This command:

ffmpeg-normalize "AC-DC - Back in Black.mp3" -c:a libmp3lame -e="-q:a 2" -d

results in "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

No difference using the = or not.

**Comment by slhck** [comment] 2018-05-05 21:33
That's weird, I cannot reproduce the problem:

```
python3 -m ffmpeg_normalize test/test.mp4 -c:a libmp3lame -e="-q:a 2" -d
```
works fine. Same for Python 2. Also works if you leave out the `=` and there is no option clash.

Make sure you are running the latest version of the code I pushed a few hours ago.

**Comment by TanMan1217** [comment] 2018-05-07 19:28
I had not realized you'd updated the code. I'll update in a day or two and retry. Been a little busy. Thanks very much for your help.

**Comment by TanMan1217** [comment] 2018-05-08 19:18
OK. Back onto this. I tried to update ffmpeg-normalize using the normal install ("pip3 install ffmpeg-normalize"), but that just says I already have the latest. In addition, it only installs 1.3.2. The current version appears to be 1.3.4, so I changed the install to "pip3 install ffmpeg-normalize==1.3.4", and that seems to have worked.

Then I ran this command:

ffmpeg-normalize "Aerosmith - Dream On.mp3" -c:a libmp3lame -e="-q:a 2" -ext mp3

The result was a normalized mp3 with VBR and an average bitrate of 174kb/s. So it's working now. Thank you so much!

One additional issue. Running this command results in a warning in tqdm:

c:\users\XXX\appdata\local\programs\python\python36\lib\site-packages\tqdm\_monitor.py:89: TqdmSynchronisationWarning: Set changed size during iteration (see https://github.com/tqdm/tqdm/issues/481)
  TqdmSynchronisationWarning)

This didn't seem to interfere with the creation of the normalized mp3, but I also did not get a progress bar.

**Comment by slhck** [comment] 2018-05-09 06:55
>  In addition, it only installs 1.3.2. The current version appears to be 1.3.4, so I changed the install to "pip3 install ffmpeg-normalize==1.3.4", and that seems to have worked.

That's a bug with pip that I've experienced myself, not sure why this sometimes occurs.
Glad it worked now.

> One additional issue. Running this command results in a warning in tqdm

What terminal / platform are you running this on? Could be a Windows thing.

**Comment by TanMan1217** [comment] 2018-05-09 15:43
I'm on Windows 10 x64 1803 Build 17134.48, using Python 3.6.

**Comment by slhck** [comment] 2018-05-11 23:06
I've seen a similar warning recently on macOS, so I'll investigate what's up with that if it shows up again.

**Closed by slhck** 2018-05-11 23:06 UTC
Labels: need-feedback, question
