### ISSUE TITLE
Output video streams incorrectly tagged as having a variable frame rate

### ISSUE THREAD

**Issue by fredflintis** [slhck/ffmpeg-normalize#95] opened 2019-03-27 00:26 UTC
**Expected behavior**
ffmpeg-normalize should process only the audio streams while leaving the video stream untouched.

**Actual behavior**
The program messes with the video metadata, marking certain output files as having a variable frame rate mode, even though the input files have a constant frame rate.

I've tried running several files with different frame rates through ffmpeg-normalize, writing down the results in the table below. Most blu-rays I ran through the program were incorrectly tagged. Out of half a dozen blu-rays, only one was correctly tagged as having a constant frame rate. Why, I have no clue.

If the source file has an unspecified frame rate mode, it seems ffmpeg-normalize will assume the file has a variable frame rate, even though the frame rate is in fact constant.

Source | Input FPS | Output FPS | Input FPS mode | Output FPS mode
------------ |------------ | ------------ | ------------- | ------------
Blu-ray (Several) | 23.976 (24000/1001) FPS | 23.976 FPS| Constant | **Variable**
Blu-ray (One example) | 23.976 (24000/1001) FPS | 23.976 (24000/1001) FPS | Constant | Constant
TV | 25.000 FPS | 25.000 FPS | Constant | Constant
YouTube | 29.970 (29970/1000) FPS | 29.970 (29970/1000) FPS | Constant | Constant
Home video | 29.970 (30000/1001) FPS | 29.970 FPS | Unspecified* | **Variable**

*Identified as Constant by MKVToolNix

**Command**
The exact command you were trying to run:

```
ffmpeg-normalize input.mkv -c:a aac -b:a 192k -ar 48000 -e="-ac 2"
```

**Environment (please complete the following information):**
- [ ] Windows 10
- [ ] Python 3.7
- [ ] ffmpeg 4.1.1

**Comment by slhck** [comment] 2019-03-27 09:55
Please show the output of an ffmpeg-normalize command where you say you get variable framerate as output, using the `--debug` flag.

Please also show an example of `ffmpeg -i input.mkv` and `ffmpeg -i normalized-input.mkv`.

Thanks!

**Comment by fredflintis** [comment] 2019-03-27 22:04
Okay, here's the info you requested, from one of the files being incorrectly tagged:

[debug log.txt](https://github.com/slhck/ffmpeg-normalize/files/3015332/debug.log.txt)
[ffmpeg input.txt](https://github.com/slhck/ffmpeg-normalize/files/3015375/ffmpeg.input.txt)
[ffmpeg normalized-input.txt](https://github.com/slhck/ffmpeg-normalize/files/3015376/ffmpeg.normalized-input.txt)

Also, simply remuxing the file with ffmpeg doesn't change the frame rate mode.

**Comment by slhck** [comment] 2019-03-28 08:51
Thanks. That's interesting – I don't see any indication of the actual video stream changing its properties. After all, it's just copied over to the output file.

By "simply remuxing the file with ffmpeg", do you mean this?

    ffmpeg -i input.mkv -c copy -map 0 output.mkv

One reason could be the mapping of additional metadata, so my guess is that this command will result in the same behavior (indicated CFR → VFR):

    ffmpeg -i input.mkv -map_metadata 0 -map_metadata:s:a:0 0:s:a:0 -map_metadata:s:v:0 0:s:v:0 -map_metadata:s:s:0 0:s:s:0 -map_metadata:s:s:1 0:s:s:1 -map_chapters 0 -map 0:0 -map 0:1 -map 0:2 -map 0:3 -c copy output.mkv

Could you perhaps check that? Or send me a sample that exhibits this behavior.

Also, have a look at:

- https://gitlab.com/mbunkus/mkvtoolnix/wikis/Wrong-frame-rate-displayed
- https://github.com/HandBrake/HandBrake/issues/1396

Particularly:

> 1) Matroska does not actually contain a metadata field for frame rate, constant or variable; and 2) in the absence of the spec-compliant metadata field, MediaInfo just tries to guess, I don't think what you're looking for is properly a bug or enhancement

So, what you're seeing in mkvtoolnix is most likely a false indication. Does it actually cause any problems?

**Comment by fredflintis** [comment] 2019-03-29 09:31
> By "simply remuxing the file with ffmpeg", do you mean this?

Yes, exactly.
>my guess is that this command will result in the same behavior (indicated CFR → VFR):

I tried it, but the resulting file did not change its frame rate mode.

Looking at these:
[https://obsproject.com/mantis/view.php?id=1115](https://obsproject.com/mantis/view.php?id=1115)
[https://stackoverflow.com/questions/52214177/ffmpeg-changes-bitrate-to-variable-when-remuxing](https://stackoverflow.com/questions/52214177/ffmpeg-changes-bitrate-to-variable-when-remuxing)

It does seem to be a problem with ffmpeg, but I haven't actually noticed this behavior with ffmpeg itself, only ffmpeg-normalize.

**Comment by slhck** [comment] 2019-03-29 11:56
> I tried it, but the resulting file did not change its frame rate mode.

That's interesting. Do you have a sample I can try with?

> It does seem to be a problem with ffmpeg

Thanks for the links. What I can read from these posts is that it's actually due to how MediaInfo or mkvtoolnix estimate the CFR/VFR property in MKV, since the container doesn't store that info directly. The timing of the frames in the video stream is not changed when doing a `-c:v copy`.

I'd like to see the timestamps of the frames of the affected video file.

> I haven't actually noticed this behavior with ffmpeg itself, only ffmpeg-normalize.

The `ffmpeg-normalize` script doesn't do anything special here. As you can see from the debug log, filtering is done on the audio stream(s); everything else is copied over as-is. So it should be possible to reproduce this with a “pure” ffmpeg command.

**Comment by slhck** [comment] 2019-03-29 11:57
Oh, and I notice that this only affects files with non-integer framerates, which leads me to believe that it could be simply a rounding issue when estimating timestamp deltas.

**Comment by fredflintis** [comment] 2019-03-30 01:27
Ok, here's a sample:

[sample.zip](https://github.com/slhck/ffmpeg-normalize/files/3024973/sample.zip)

Oh, and I've done some more testing, and it seems outputting the file to PCM, FLAC or Vorbis produces an unaltered video stream. Using the AAC, libmp3lame or libopus encoder changes the frame mode to variable. I haven't tried libfdk_aac since I don't have it installed. Try it out and see if you get the same.

**Comment by slhck** [comment] 2019-04-05 18:20
Sorry for not responding earlier. Thanks for providing the sample. I'll have a look and see if I can find a workaround. I'm sure it has to do with how audio and video samples are synchronized in the container. I'll keep this open for now.

**Comment by slhck** [comment] 2019-04-05 19:05
I could reproduce the issue with a simple command:

```
ffmpeg -i sample.mkv -c:v copy -c:a aac normalized/sample-aac.mkv
ffmpeg -i sample.mkv -c:v copy -c:a pcm_s16le normalized/sample-pcm.mkv
```

The first results in `mediainfo` reporting as variable framerate, the second is constant framerate. But `mediainfo` is not to blame; the container packet timestamp differences are huge for the AAC variant, while they're somewhat constant for PCM:

```
➜ ffprobe -loglevel error -hide_banner normalized/sample-aac.mkv -select_streams v -show_frames -show_entries frame=pkt_pts_time -of compact=nk=1:p=0 | head -n 10 | awk 'NR>1{print $1-p} {p=$1}'
0.063
0.041
0.042
0.021
0.063
0.041
0.042
0.042
0.041

➜ ffprobe -loglevel error -hide_banner normalized/sample-pcm.mkv -select_streams v -show_frames -show_entries frame=pkt_pts_time -of compact=nk=1:p=0 | head -n 10 | awk 'NR>1{print $1-p} {p=$1}'
0.045
0.041
0.042
0.039
0.045
0.041
0.042
0.042
0.041
```

I don't really have time to debug and look for the cause of that, but I'm sure someone on the FFmpeg mailing list or bug tracker would know why that is.

**Comment by slhck** [comment] 2019-06-02 16:37
Closing this as an upstream bug.

**Closed by slhck** 2019-06-02 16:37 UTC
Labels: bug, upstream-bug
