### ISSUE TITLE
Skip files that already meet (or close enough) the requested normalization level

### ISSUE THREAD

**Issue by milnak** [slhck/ffmpeg-normalize#195] opened 2022-11-16 17:17 UTC
**Is your feature request related to a problem? Please describe.**
When running ffmpeg-normalize its possible that a file is already considered normalized (or close enough) - renormalizing the file with a lossy format (e.g. mp3) isn't ideal - for lossless formats like flac this is fine.

**Describe the solution you'd like**
Is there a way to have ffmpeg-normalize skip files that are already considered normalized?

**Describe alternatives you've considered**
I considered running the ffmpeg command myself and look at the resultant values and only call ffmpeg-normalize for remaining files, but it seems like this app could do a better job than I could.

**Additional context**
None.

**Comment by slhck** [comment] 2022-11-16 20:10
This is a duplicate of https://github.com/slhck/ffmpeg-normalize/issues/50.

It used to be possible but I haven't found time to implement it for the v1.0 rewrite.

**Comment by slhck** [comment] 2023-01-01 08:29
Not planned for now, since I believe it's easier from a workflow perspective to just run the normalization again — if you choose to re-encode with a lossless codec, that won't hurt and ensure all your files are processed the same way.

**Closed by slhck** 2023-01-01 08:29 UTC
