### ISSUE TITLE
Loudness normalization for files with very low sound

### ISSUE THREAD

**Issue by timlac** [slhck/ffmpeg-normalize#252] opened 2024-01-24 15:11 UTC
**Problem**
I'm trying to achieve loudness normalization for the purpose of achieving a stable loudness for a collection of files in which the sound is quite low for most files. It works well for most files, but for certain files the sound so low that the loudness even after normalization does not seem to be effected. The files consists of actor portraying different emotions, uttering only a few words. For some emotions they speak very low, barely audible. 

I'm currently using the default settings, I wonder if there is some parameter that might be suitable to increase the loudness even in files that have very low volume.

**Comment by slhck** [comment] 2024-01-24 15:33
Hard to reproduce without a sample, but I think R128 is not very reliable with short and low volume. Can you try setting simple peak normalization and see if that produces better results? (`-nt peak`)

**Comment by timlac** [comment] 2024-01-24 15:41
Alright so it actually seems like peak normalization does the trick, thank you! Though I'm no audio expert so I have no idea why. I was under the impression that loudness normalization was the way to go if the objective is to achieve a consistent volume for all files...

Here's a sample file:
https://github.com/slhck/ffmpeg-normalize/assets/32488097/2bb82dad-6f61-479f-a22b-e708d0e0f3d7

**Comment by slhck** [comment] 2024-01-24 19:11
Great to hear that peak normalization worked for you. The reason why EBU-type loudness normalization might not be that effective is that it is based on standard audio dynamics, but in your case, where the volume is extremely low, you'd have to apply some pre-gain for the algorithm to detect something useful.

Peak normalization simply amplifies the audio signal so that the highest peak reaches a certain level (e.g. 0 dBFS; can't get higher than that, otherwise it will clip). This can make quiet sounds more audible, but it does not consider the perceived loudness or dynamic range. It's a more straightforward method and can be more effective for files with very low sound like yours — when the `loudnorm` filter simply doesn't have enough gain to do anything useful.

If consistency across all files is your goal, you might have to use a combination of both methods. For example, you could use peak normalization to bring the quieter files up to a more standard level and then apply loudness normalization to the entire collection for uniformity.

Closing this for now, but if you encounter any more issues or have questions, feel free to reach out!

**Closed by slhck** 2024-01-24 19:11 UTC
