### ISSUE TITLE
Input and output order

### ISSUE THREAD

**Issue by homocomputeris** [slhck/ffmpeg-normalize#132] opened 2020-07-22 12:36 UTC
In -h output comes before input (which does not work):
```
ffmpeg-normalize [-h] [-o OUTPUT [OUTPUT ...]]
    ...
    input [input ...]
```
in the examples it's vice versa:
```
ffmpeg-normalize *.mkv -c:a aac -b:a 192k
ffmpeg-normalize input.mp3 -c:a libmp3lame -b:a 320k -o output.mp3
```

Probably, -h should read something like
```
ffmpeg-normalize [-h]  input [input ...]
                    [-o OUTPUT [OUTPUT ...]] [-of OUTPUT_FOLDER] [-f]
                    [-d] [-v] [-n] [-pr] [--version] [-nt {ebu,rms,peak}]
                    [-t TARGET_LEVEL] [-p] [-lrt LOUDNESS_RANGE_TARGET]
                    [-tp TRUE_PEAK] [--offset OFFSET] [--dual-mono]
                    [-c:a AUDIO_CODEC] [-b:a AUDIO_BITRATE]
                    [-ar SAMPLE_RATE] [-koa] [-prf PRE_FILTER]
                    [-pof POST_FILTER] [-vn] [-c:v VIDEO_CODEC] [-sn]
                    [-mn] [-cn] [-e EXTRA_OUTPUT_OPTIONS]
                    [-ofmt OUTPUT_FORMAT] [-ext EXTENSION]
```

**Comment by slhck** [comment] 2020-07-22 15:21
Thanks for pointing this out. The issue is that there are mutliple input and output file names (`nargs='+'). Indeed, specifing input after output would create ambiguous command lines:

```
python3 -m ffmpeg_normalize -o test-out.mkv test/test.wav
```

Does this mean you want two output files or one output/one input file?

The issue is that argparse doesn't generate the correct usage string. I'll have a look into that and see if it can be solved without completely changing the command-line interface.

**Comment by slhck** [comment] 2020-07-22 15:37
Released in 1.20.1.

**Closed** 2020-07-22 15:36 UTC

**Comment by homocomputeris** [comment] 2020-07-22 22:52
I believe that https://github.com/slhck/ffmpeg-normalize/blob/master/README.md#usage also needs an update

**Comment by slhck** [comment] 2020-07-23 06:12
Fixed that too, thanks.

**Comment by homocomputeris** [comment] 2023-04-24 13:48
I believe the `-h` should be updated in the readme too, because input goes after output:

> ffmpeg-normalize [-h]
>     **[-o OUTPUT [OUTPUT ...]]** [-of OUTPUT_FOLDER]
>     [-f] [-d] [-v] [-q] [-n] [-pr]
>     [--version]
>     [-nt {ebu,rms,peak}]
>     [-t TARGET_LEVEL] [-p] [-lrt LOUDNESS_RANGE_TARGET] [-tp TRUE_PEAK] [--offset OFFSET] [--dual-mono] [--dynamic]
>     [-c:a AUDIO_CODEC] [-b:a AUDIO_BITRATE] [-ar SAMPLE_RATE] [-koa]
>     [-prf PRE_FILTER] [-pof POST_FILTER]
>     [-vn] [-c:v VIDEO_CODEC]
>     [-sn] [-mn] [-cn]
>     [-ei EXTRA_INPUT_OPTIONS] [-e EXTRA_OUTPUT_OPTIONS]
>     [-ofmt OUTPUT_FORMAT] [-ext EXTENSION]
>     **input [input ...]**

https://github.com/slhck/ffmpeg-normalize#usage

```shell
ffmpeg-normalize -o 0b2ee160229e78d257214df86907a17e.opus 0b2ee160229e78d257214df86907a17e.mp3
usage: ffmpeg-normalize [-h] [-o OUTPUT [OUTPUT ...]] [-of OUTPUT_FOLDER] [-f]
                        [-d] [-v] [-q] [-n] [-pr] [--version]
                        [-nt {ebu,rms,peak}] [-t TARGET_LEVEL] [-p]
                        [-lrt LOUDNESS_RANGE_TARGET]
                        [--keep-loudness-range-target]
                        [--keep-lra-above-loudness-range-target] [-tp TRUE_PEAK]
                        [--offset OFFSET] [--dual-mono] [--dynamic]
                        [-c:a AUDIO_CODEC] [-b:a AUDIO_BITRATE]
                        [-ar SAMPLE_RATE] [-koa] [-prf PRE_FILTER]
                        [-pof POST_FILTER] [-vn] [-c:v VIDEO_CODEC] [-sn] [-mn]
                        [-cn] [-ei EXTRA_INPUT_OPTIONS]
                        [-e EXTRA_OUTPUT_OPTIONS] [-ofmt OUTPUT_FORMAT]
                        [-ext EXTENSION]
                        input [input ...]
```

**Comment by slhck** [comment] 2023-04-24 15:06
Updated in b5d7305b2cb1072e0075ab19f41c31f4c19f1a5d

Does that make more sense?

Thanks for bringing it up.

**Comment by homocomputeris** [comment] 2023-04-24 16:45
Yeah, thanks a lot!
